### ISSUE TITLE
[bug] cpu占用高

### ISSUE THREAD

**Issue by bszydxh** [tty228/udp_turn_off#1]
你好!未连接网络时程序的阻塞进程占用cpu高,希望解决

**Comment by bszydxh** [comment]
![image](https://user-images.githubusercontent.com/79249935/156027654-8f89c9c9-1555-4194-9f5c-18f85f4e4646.png)

**Comment by tty228** [comment]
好久没翻代码了，不知道有没有注释，还看不看得懂（哭笑脸）
忙完这阵就看看

**Comment by tty228** [comment]
已修复
